services:
  schedule_bot:
    build: .
    image: otu_schedule_bot
    container_name: schedule_bot
    restart: always
    environment:
      - TG_API_KEY=${TG_API_KEY}
      - DB_PASSWORD=${DB_PASSWORD}
      - TZ=Europe/Moscow
    depends_on:
      - postgres_db  # Зависимость от контейнера с БД

  postgres_db:
    image: postgres
    container_name: otu_schedule_postgres
    restart: always
    environment:
      POSTGRES_DB: schedule
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "7546:5432"
      - "443:443"
#    command: -c 'listen_addresses=*'