services:
  schedule_bot:
    image: otu_schedule_bot
    container_name: schedule_bot
    restart: always
    environment:
      - TG_API_KEY=${TG_API_KEY}
      - DB_PASSWORD=${DB_PASSWORD}
      - TZ=Europe/Moscow
    command: python tg_bot.py
    depends_on:
      - postgres_db

  parser:
    image: otu_schedule_bot
    container_name: schedule_parser
    restart: "no"
    command: python parse_timetables.py
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - TZ=Europe/Moscow
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres
    container_name: otu_schedule_postgres
    restart: always
    environment:
      POSTGRES_DB: schedule
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "7546:5432"
#    command: -c 'listen_addresses=*'